import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarWrapper from "@/components/SidebarWrapper";
import { headers } from "next/headers"; // ✅ Import `headers()` to get pathname

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers(); // ✅ Await `headers()` correctly
  const pathname = headerList.get("next-url") || ""; // ✅ Now it works!
  const isLoginPage = pathname === "/login"; // ✅ Check if it's the login page

  return (
    <html lang="en" className="h-full">
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>

        {isLoginPage ? (
          // ✅ Login Page - No Sidebar, Full Page
          <div className="h-screen flex items-center justify-center">
            {children}
          </div>
        ) : (
          // ✅ Dashboard Layout - Sidebar + Main Content
          <div className="flex  h-screen">
            <SidebarWrapper /> {/* ✅ Show Sidebar only when not on login */}
            <div className=" flex-1">{children}</div>
          </div>
        )}
      </body>
    </html>
  );
}
